CHART_REPO = [
    {"name": "Bar Chart", "data_type": "categorical", "use_cases": ["comparison", "ranking", "sales comparison"]},
    {"name": "Horizontal Bar Chart", "data_type": "categorical", "use_cases": ["ranking", "long labels", "category comparison"]},
    {"name": "Grouped Bar Chart", "data_type": "categorical", "use_cases": ["segment comparison", "cohort comparison"]},
    {"name": "Stacked Bar Chart", "data_type": "categorical", "use_cases": ["composition", "portfolio mix", "category share"]},
    {"name": "100% Stacked Bar Chart", "data_type": "categorical", "use_cases": ["relative composition", "percent share"]},
    {"name": "Line Chart", "data_type": "time_series", "use_cases": ["trend", "forecast", "monthly revenue"]},
    {"name": "Multi-series Line Chart", "data_type": "time_series", "use_cases": ["trend comparison", "cohort trends"]},
    {"name": "Area Chart", "data_type": "time_series", "use_cases": ["cumulative totals", "composition over time"]},
    {"name": "Stacked Area Chart", "data_type": "time_series", "use_cases": ["stacked composition", "share over time"]},
    {"name": "Streamgraph", "data_type": "time_series", "use_cases": ["flow composition", "topic trends"]},
    {"name": "Sparkline", "data_type": "time_series", "use_cases": ["inline trend", "micro-trend"]},
    {"name": "Histogram", "data_type": "univariate", "use_cases": ["distribution", "frequency", "value spread"]},
    {"name": "Box Plot", "data_type": "univariate", "use_cases": ["distribution summary", "outliers", "quartiles"]},
    {"name": "Violin Plot", "data_type": "univariate", "use_cases": ["distribution density", "shape comparison"]},
    {"name": "Scatter Plot", "data_type": "bivariate", "use_cases": ["correlation", "relationship", "outlier detection"]},
    {"name": "Bubble Chart", "data_type": "multivariate", "use_cases": ["three variable comparison", "portfolio analysis"]},
    {"name": "Hexbin Plot", "data_type": "bivariate", "use_cases": ["density", "overplotting"]},
    {"name": "Pareto Chart", "data_type": "categorical", "use_cases": ["80/20 analysis", "priority issues"]},
    {"name": "Waterfall Chart", "data_type": "financial", "use_cases": ["profit_loss", "impact analysis", "financial breakdown"]},
    {"name": "Funnel Chart", "data_type": "sequential", "use_cases": ["conversion", "drop-off analysis", "sales funnel"]},
    {"name": "Sankey Diagram", "data_type": "flow", "use_cases": ["flow visualization", "user journey", "value flow"]},
    {"name": "Alluvial Diagram", "data_type": "flow", "use_cases": ["categorical flow", "state changes"]},
    {"name": "Treemap", "data_type": "hierarchical", "use_cases": ["part-to-whole", "hierarchy size", "drilldown"]},
    {"name": "Sunburst Chart", "data_type": "hierarchical", "use_cases": ["nested composition", "hierarchical categories"]},
    {"name": "Icicle Chart", "data_type": "hierarchical", "use_cases": ["hierarchy", "structure view"]},
    {"name": "Dendrogram", "data_type": "hierarchical", "use_cases": ["cluster hierarchy", "cluster analysis"]},
    {"name": "Radar Chart", "data_type": "multivariate", "use_cases": ["profile comparison", "attribute comparison"]},
    {"name": "Parallel Coordinates", "data_type": "multivariate", "use_cases": ["high-dimensional comparison", "pattern detection"]},
    {"name": "Heatmap", "data_type": "matrix", "use_cases": ["correlation", "intensity matrix", "activity patterns"]},
    {"name": "Calendar Heatmap", "data_type": "time_series", "use_cases": ["daily activity", "seasonality", "calendar pattern"]},
    {"name": "Gantt Chart", "data_type": "timeline", "use_cases": ["project schedule", "task tracking"]},
    {"name": "Annotated Timeline", "data_type": "timeline", "use_cases": ["milestones", "event sequence"]},
    {"name": "Scree Plot", "data_type": "pca", "use_cases": ["variance explained", "component selection"]},
    {"name": "ROC Curve", "data_type": "ml_evaluation", "use_cases": ["classifier performance", "false_positive_tradeoff"]},
    {"name": "Precision-Recall Curve", "data_type": "ml_evaluation", "use_cases": ["imbalanced classifier evaluation", "precision_recall_tradeoff"]},
    {"name": "Cohort Retention Heatmap", "data_type": "cohort", "use_cases": ["retention", "cohort analysis"]},
    {"name": "Retention Curve", "data_type": "cohort", "use_cases": ["user survival", "churn analysis"]},
    {"name": "Network Graph", "data_type": "relational", "use_cases": ["connections", "influence mapping"]},
    {"name": "Chord Diagram", "data_type": "relational", "use_cases": ["inter-group flows", "mutual flows"]},
    {"name": "Chord (weighted)", "data_type": "relational", "use_cases": ["weighted interconnections", "trade flows"]},
    {"name": "Geo Choropleth Map", "data_type": "geospatial", "use_cases": ["regional intensity", "map-based KPI"]},
    {"name": "Proportional Symbol Map", "data_type": "geospatial", "use_cases": ["location magnitude", "point counts"]},
    {"name": "Flow Map", "data_type": "geospatial", "use_cases": ["movement between locations", "shipments"]},
    {"name": "Cartogram", "data_type": "geospatial", "use_cases": ["size-by-metric map", "storytelling map"]},
    {"name": "Ternary Plot", "data_type": "multivariate", "use_cases": ["three-part composition", "mixture proportions"]},
    {"name": "Waffle Chart", "data_type": "percentage", "use_cases": ["part-to-whole", "small composition"]},
    {"name": "Donut Chart", "data_type": "percentage", "use_cases": ["market share", "composition"]},
    {"name": "Bullet Chart", "data_type": "single_value", "use_cases": ["kpi vs target", "performance tracking"]},
    {"name": "KPI Tile", "data_type": "single_value", "use_cases": ["single metric", "dashboard kpi"]},
    {"name": "Tornado Chart", "data_type": "sensitivity", "use_cases": ["sensitivity analysis", "one-way sensitivity"]},
    {"name": "Decision Matrix (Weighted Scoring)", "data_type": "decision", "use_cases": ["option evaluation", "weighted decision"]},
    {"name": "Risk Heat Map", "data_type": "risk", "use_cases": ["risk_prioritization", "probability_vs_impact"]},
]