INFOGRAPHIC_REPO = [
    {"name": "Waterfall Chart (Consulting Style)", "use_cases": ["profit/loss breakdown", "impact analysis", "financial storytelling"]},
    {"name": "Gantt Chart", "use_cases": ["project timelines", "workstream progress"]},
    {"name": "Heatmap", "use_cases": ["intensity mapping", "correlation matrix", "regional performance"]},
    {"name": "Tree Map", "use_cases": ["hierarchical distribution", "subcategory share"]},
    {"name": "Sankey Diagram", "use_cases": ["flow visualization", "resource allocation"]},
    {"name": "Radar (Spider) Chart", "use_cases": ["capability benchmarking", "attribute comparison"]},
    {"name": "Pyramid Diagram", "use_cases": ["hierarchy visualization", "demographics"]},
    {"name": "Matrix (2x2, 3x3)", "use_cases": ["positioning", "prioritization", "strategic frameworks"]},
    {"name": "SWOT Matrix", "use_cases": ["strengths", "weaknesses", "opportunities", "threats"]},
    {"name": "Porter’s Five Forces Diagram", "use_cases": ["competitive analysis", "industry structure"]},

    {"name": "BCG Growth-Share Matrix", "use_cases": ["portfolio analysis", "market share vs growth"]},
    {"name": "Ansoff Matrix", "use_cases": ["growth strategy visualization"]},
    {"name": "Value Chain Diagram", "use_cases": ["operational breakdown", "process mapping"]},
    {"name": "Journey Map", "use_cases": ["customer journey", "experience stages"]},
    {"name": "Ecosystem Map", "use_cases": ["stakeholder mapping", "market players overview"]},
    {"name": "Venn Diagram", "use_cases": ["overlap", "intersection analysis"]},
    {"name": "Circular Flow Diagram", "use_cases": ["processes", "cyclical models"]},
    {"name": "Org Chart", "use_cases": ["organizational structure", "governance"]},
    {"name": "Timeline / Roadmap", "use_cases": ["milestones", "strategic roadmap"]},
    {"name": "Bridge Diagram", "use_cases": ["current vs future state", "change drivers"]},

    {"name": "Market Map", "use_cases": ["competitive landscape visualization"]},
    {"name": "Ecosystem Landscape", "use_cases": ["industry players", "alliances", "ecosystem orchestration"]},
    {"name": "Icon-Based Infographic", "use_cases": ["visual storytelling", "qualitative insights"]},
    {"name": "Gauge / Speedometer", "use_cases": ["KPI tracking", "performance index"]},
    {"name": "Bullet Chart (Consulting Style)", "use_cases": ["performance vs benchmark", "target achievement"]},
    {"name": "Tree Diagram", "use_cases": ["hierarchical breakdown", "logical flows"]},
    {"name": "Decision Tree", "use_cases": ["strategic choices", "risk pathways"]},
    {"name": "Fishbone Diagram (Ishikawa)", "use_cases": ["root cause analysis"]},
    {"name": "Chord Diagram", "use_cases": ["relationship mapping", "inter-group flows"]},
    {"name": "Tornado Diagram", "use_cases": ["sensitivity analysis", "risk ranges"]},

    {"name": "Customer Journey Infographic", "use_cases": ["persona flows", "touchpoint visualization"]},
    {"name": "Capability Map", "use_cases": ["enterprise capabilities", "function benchmarking"]},
    {"name": "Maturity Model", "use_cases": ["process maturity", "digital transformation stage"]},
    {"name": "Operating Model Diagram", "use_cases": ["org operating model", "processes and enablers"]},
    {"name": "Business Model Canvas", "use_cases": ["startup strategy", "business model articulation"]},
    {"name": "Lean Canvas", "use_cases": ["entrepreneurship", "problem-solution fit"]},
    {"name": "OKR Infographic", "use_cases": ["objectives", "key results alignment"]},
    {"name": "Strategy Map", "use_cases": ["cause-effect relationships", "balanced scorecard"]},
    {"name": "Balanced Scorecard Layout", "use_cases": ["performance management", "KPI alignment"]},
    {"name": "Horizon Model (McKinsey 3 Horizons)", "use_cases": ["growth planning", "innovation strategy"]},

    {"name": "Scenario Planning Diagram", "use_cases": ["uncertainty visualization", "strategic foresight"]},
    {"name": "Risk Heatmap", "use_cases": ["risk likelihood vs impact", "portfolio risk view"]},
    {"name": "Stakeholder Map", "use_cases": ["influence vs interest", "stakeholder prioritization"]},
    {"name": "System Dynamics Diagram", "use_cases": ["feedback loops", "complex system visualization"]},
    {"name": "Change Curve Infographic", "use_cases": ["organizational change", "adoption stages"]},
    {"name": "Value Proposition Canvas", "use_cases": ["customer jobs/pains/gains", "value mapping"]},
    {"name": "Operating Rhythm Diagram", "use_cases": ["cadence of meetings", "governance model"]},
    {"name": "Governance Framework", "use_cases": ["decision rights", "board structures"]},
    {"name": "Transformation Roadmap", "use_cases": ["phases of transformation", "initiative sequencing"]},
    {"name": "North Star Framework", "use_cases": ["vision alignment", "strategic direction"]}
]